baseURL = "/"
title = "christianson.ai"
theme = "PaperMod"
languageCode = "en-us"
defaultContentLanguage = "en"

enableRobotsTXT = true
buildDrafts = false
buildFuture = false
buildExpired = false

[params]
  description = "My personal blog"
  author = "Andrew I. Christianson"
  mainSections = ["posts"]
  defaultTheme = "auto"
  ShowReadingTime = true
  ShowShareButtons = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  ShowFullTextinRSS = true
  disableSpecial1stPost = false
  displayFullLangName = true
  comments = false

  [params.assets]
    favicon = "favicon.ico"
    favicon16x16 = "favicon-16x16.png"
    favicon32x32 = "favicon-32x32.png"
    apple_touch_icon = "apple-touch-icon.png"
    safari_pinned_tab = "safari-pinned-tab.svg"

[params.homeInfoParams]
  Title = "Hello ðŸ‘‹"
  Content = "Welcome to the official blog of Andrew I. Christianson."

[[params.socialIcons]]
  name = "github"
  url = "https://github.com/ai-christianson"

[[params.socialIcons]]
  name = "tiktok"
  url = "https://www.tiktok.com/@ai.christianson"

[[params.socialIcons]]
  name = "x"
  url = "https://x.com/ai_christianson"

[[params.socialIcons]]
  name = "instagram"
  url = "https://www.instagram.com/ai.christianson/"

[[params.socialIcons]]
  name = "youtube"
  url = "https://www.youtube.com/@AndrewIChristianson/shorts"

[[params.socialIcons]]
  name = "linkedin"
  url = "https://www.linkedin.com/in/ai-christianson"

[menu]
  [[menu.main]]
    name = "Archive"
    url = "archives"
    weight = 10
  [[menu.main]]
    name = "Search"
    url = "search/"
    weight = 20
  [[menu.main]]
    name = "Tags"
    url = "tags/"
    weight = 30
